name: Java with Nexus Repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://localhost:8081/
        username: admin
        password: ${{ secrets.PASSWORD }}
        format: raw
        repository: http://localhost:8081/repository/luarocks-local/
        assets: extension=.all.rock
        filename: ./kong-plugin-internal-basic-auth-1.0.0-1.all.rock
