name: Java with Nexus Repository

on: [push]

jobs:
  Create plguin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install lua and luarocks
      run: |
        sudo apt update
        sudo apt install lua5.4 -y
        sudo apt install luarocks -y
    - name: create plugin
      run: |
        git config --global user.name "kongTeam"
        git config --global user.email "kongTeam@gmail.com"
        git clone https://github.com/Kong/kong-plugin.git

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

